---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/inova7/coordenacao.inova7.com.br/
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan route:clear
    - php artisan migrate --force