---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/inova7/coordenacao.inova7.com.br/
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH
    - export PATH="/home1/inova7:$PATH"
    - php /home1/inova7/composer install --no-interaction --prefer-dist --no-progress --no-dev
    - php /home1/inova7/composer dump-autoload --no-dev
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan route:clear
    - php artisan migrate --force