deployment:
  tasks:
    - export DeploymentPath=/home1/inova7/coordenacao.inova7.com.br
    - cd $DeploymentPath
    - composer install --no-dev --optimize-autoloader
    - php artisan config:cache
    - php artisan route:cache
    - php artisan migrate --force